### ISSUE TITLE
Using In a Package

### ISSUE THREAD

**Issue by secondmanveran** [shomisha/laravel-console-wizard#3]
Hey there, this is a great package. I'm attempting to include it in a package I have that has a ton of generators, but it doesn't seem to be finding the classes.

I noticed the ServiceProvider only provides the `GenerateWizardWizard` command so I skipped loading that and just loaded that command into my GeneratorServiceProvider.

It works fine from inside a Laravel app via a generated console command, but when I call a command from my package I get an error that the `$answer` property doesn't exist:

> Undefined property: MyPackage\Console\Commands\ScaffoldMakeCommand::$answer

Very strange, the steps work fine, it loads, asks all the questions perfectly, then blows up.

Any ideas?

**Comment by shomisha** [comment]
Hi! Thanks for using the package and I'm very glad you like it :) 

I scanned through the library a bit and couldn't find a single reference to an `$answer` property. The `WizardCore` has an `$answers` (plural) property which is a Collection of answers provided by the user, but nowhere is it accessed in singular form.

Is it possible you're trying to access the `$answers` property and accidentally omitted the last "s"?  If that's not the case you can share a link to your package and I can try and help find what's wrong
